In [2]:
import scipy.io
import pandas as pd
import numpy as np
import glob
import pickle
import os
import matplotlib.pyplot as plt
import matplotlib
import seaborn as sns
%matplotlib inline

# Save out Emma's data into a format I can use
- get emmma's data from mat file
- save out csv files for my model scripts to run. 

In [3]:
dictt = scipy.io.loadmat('../data/data_emmas/DataMatrix_AllfMRI_FinalSubjects.mat')

/Users/chris/anaconda/lib/python3.6/site-packages/scipy/io/matlab/mio.py:136: MatReadWarning: Duplicate variable name "None" in stream - replacing previous with new
Consider mio5.varmats_from_mat to split file into single variable files
  matfile_dict = MR.get_variables(variable_names)


In [4]:
dictt['BDI_fmri']

array([[  2.5,   2. ,  11. ,   1. ,   5. ,   5. ,   3. ,   2. ,   6. ,
          0. ,   5. ,   3. ,   6. ,   2. ,   3. ,  16. ,   6. ,   3. ,
          6. ,  12. ,   3. ,   1. ,   0. ,  13. ,   6. ,   0. ,   6.5,
          0. ,   2. ,   0. ,  13. ,   0. ]])

In [5]:
dictt['Trait_fmri']

array([[41, 33, 41, 41, 34, 42, 33, 32, 49, 33, 37, 39, 45, 34, 39, 53, 45,
        34, 53, 50, 36, 28, 27, 52, 29, 21, 47, 23, 24, 24, 56, 20]], dtype=uint8)

In [6]:
amb = dictt['ambiguity'][:,0]==1.0

In [7]:
dictt['choices_unambig'][:,0]==dictt['choices'][amb,0]

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True], dtype=bool)

In [8]:
dictt['choices'][~amb,0]==dictt['choices_ambig'][:,0]

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True], dtype=bool)

In [9]:
dictt['choices'][:,0]

array([1, 0, 1, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0,
       1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 1,
       0, 0, 0, 1, 0, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 1, 1,
       0, 0, 1, 1, 0, 0, 1, 1, 1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0,
       1, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0, 1, 1, 1, 0, 0,
       0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1,
       1, 1, 0, 1, 1, 1, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0,
       0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 1, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0,
       1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0], dtype=uint16)

In [6]:
# convert data into a form that is useable for my model scripts. 
MIDs = []
for sub in range(32):
    trial_array = np.empty((200,8))
    
    # basic 
    trial_array[:,0] = dictt['choices'][:,sub] # check this is right/left 
    trial_array[:,1] =dictt['ProportionNoughts_L'][sub,:]
    trial_array[:,2] =dictt['ProportionNoughts_R'][sub,:]
    trial_array[:,3] =dictt['Magnitude_Left'][sub,:]/100.0
    trial_array[:,4] =dictt['Magnitude_Right'][sub,:]/100.0
    trial_array[:,5] =dictt['Ambiguity'][sub,:]
    trial_array[:,6] =dictt['no_noughtsrevealedTOSAVEtemp'][:,sub]
    trial_array[:,7] =dictt['no_tokensrevealedTOSAVEtemp'][:,sub]
    
    # make dataFrame
    trial_data = pd.DataFrame(data=trial_array,columns=['resp_r_1','prob_o_l','prob_o_r','mag_left','mag_right','info_amb','revealed_o_r','num_revealed'])
    
    # ambiguous trials (right=ambiguous)
    trial_data['info_amb_sqrt']=np.sqrt(trial_data['info_amb'])
    trial_data.loc[trial_data['resp_r_1']>1,'resp_r_1']=np.nan
    trial_data['resp_amb_1'] = trial_data['resp_r_1']
    trial_data['ambig_r']=(trial_data['info_amb_sqrt']!=1).astype('int')
    trial_data['ambig_l']=np.zeros(len(trial_data))
    trial_data['gain_or_loss_trial']='shock'
    trial_data['mag_ambig']=trial_data['mag_right']
    trial_data['mag_unambig']=trial_data['mag_left']
    # changed this to say 'x' instead of 'o'. (not substantive change)
    # for the scripts that hanna wrote
    trial_data['prob_x_unambig']=trial_data['prob_o_l']
    trial_data['prob_x_ambig']=trial_data['prob_o_r']

    trial_data['prob_x_l']=trial_data['prob_o_l'].copy()
    trial_data['prob_x_r']=trial_data['prob_o_r'].copy()
   
    trial_data['prob_o_l']=1.0-trial_data['prob_x_l']
    trial_data['prob_o_r']=1.0-trial_data['prob_x_r']
    
    trial_data['revealed_o_ambig']=trial_data['revealed_o_r'] # right side is ambig
    trial_data['revealed_x_ambig']=trial_data['num_revealed']-trial_data['revealed_o_ambig']
    trial_data['revealed_ambi']=trial_data['revealed_o_r']
    trial_data['prob_x_ambig_bayes']=(trial_data['revealed_o_r']+1)/(trial_data['num_revealed']+2)
    
    trial_data['ambiguityLevel'] = 1.0 - np.sqrt(trial_data['revealed_o_r'])
    trial_data['revealed_ambi']=trial_data['info_amb_sqrt']
    
    trial_data['gain_or_loss_trial']='gain'
    
    trial_data['MID']='S'+str(sub)
    MIDs.append('S'+str(sub))
    
    trial_data.to_csv('../data/data_emmas_logfiles_from_mat/S'+str(sub)+'.csv')




In [18]:
dictt['ProportionNoughts_L'][0,:]

array([ 0.34,  0.54,  0.88,  0.24,  0.4 ,  0.08,  0.36,  0.24,  0.24,
        0.26,  0.8 ,  0.88,  0.76,  0.44,  0.16,  0.2 ,  0.24,  0.4 ,
        0.92,  0.48,  0.12,  0.28,  0.06,  0.76,  0.48,  0.48,  0.54,
        0.12,  0.04,  0.08,  0.2 ,  0.4 ,  0.24,  0.44,  0.06,  0.72,
        0.28,  0.52,  0.42,  0.48,  0.2 ,  0.66,  0.04,  0.04,  0.4 ,
        0.58,  0.46,  0.2 ,  0.6 ,  0.88,  0.52,  0.24,  0.74,  0.52,
        0.3 ,  0.72,  0.84,  0.24,  0.52,  0.72,  0.52,  0.4 ,  0.38,
        0.92,  0.6 ,  0.62,  0.28,  0.88,  0.92,  0.64,  0.84,  0.64,
        0.8 ,  0.24,  0.94,  0.48,  0.72,  0.9 ,  0.68,  0.36,  0.36,
        0.66,  0.66,  0.52,  0.46,  0.78,  0.56,  0.76,  0.4 ,  0.52,
        0.92,  0.52,  0.8 ,  0.24,  0.96,  0.6 ,  0.76,  0.92,  0.96,
        0.8 ,  0.92,  0.72,  0.5 ,  0.48,  0.26,  0.96,  0.48,  0.38,
        0.6 ,  0.78,  0.84,  0.64,  0.92,  0.84,  0.56,  0.64,  0.5 ,
        0.64,  0.46,  0.32,  0.64,  0.64,  0.6 ,  0.88,  0.38,  0.68,
        0.72,  0.84,